# Generated by Django 3.0.2 on 2020-04-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courselist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='docs',
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
