# Generated by Django 3.0.2 on 2020-04-25 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courselist', '0002_auto_20200403_2138'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courselist.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
