# Generated by Django 3.0.2 on 2020-04-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200426_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='course',
        ),
    ]
